---
title: "Pricing Strategies of Retailers"
description: |
  Final Project Proposal for ECON-712-008
author:
  - name: Zhongtian Chen & Yihao Yuan
    url: https://github.com/yihao-yuan
    affiliation: The University of Pennsylvania
\date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Data

* Data source: a large shopping complex in Middle East operating in 15 countries.
* Carrefour data: 66 stores, data from January 2017 to March 2019.
  + Assortment data: product-package-date level; information includes regular price, promotion price, promotion time, quantities sold, quantities in stock, and wholesale price (cost); product-package information only available for some products (e.g., beverages).
  + Consumer data: 4.44 million consumers were in their loyalty rewards program; information includes basic demographics (gender and age).
  + Transaction data: about 29 million transactions made by loyalty program consumers per month across all stores; information includes timestamp, item purchased, price for each item, total spendings.
* Supplementary data
  + Credit card data: transactions used by credit card issued by the owner of the shopping complex.
  + Wi-Fi data: search history of consumers when shopping within the complex/Carrefour.

## Research Question

* What are the incentives for stores to offer discounts on products, with many of them sold well below cost?
  + Data summary based on first 1 million lines of the assortment data, 14.75% of the product-packages were on sale, and 7.42% of the product-packages were sold below cost.
  + There is large varation in margins (25th percentile: 0.9%; 75th percentile: 17.2%). Among those sold under cost, the average margin is -9.1%.

* Existing theories that may explain:
  + Intertemporal price discrimination (Hendel and Nevo, 2006, 2013). However, it cannot explain why products are sold under cost because the stores can always earn profits from both searchers and non-searchers.
  + Loss leader strategy. Stores may want to offer deep promotions on some products to attract consumers to the store to shop for other products, and maximize the overall profit. We may need to investigate transaction data to confirm whether it is true.
  + Inventory management. Some products are perishable, and stores may want to sell them before they perish. Inventory information is available 

## Research Plan

* Read full data. We have not been able to read the full assortment, which is more than 700 GB in size. We are actively working with HPCC to resolve the problem.
* Conduct more detailed descriptive analyses, and nail down the research question.
* Choose appropriate methods to answer the research question.